USE [master]
GO

/****** Object:  Database [OPRIS]    Script Date: 31.10.2016 00:22:35 ******/
CREATE DATABASE [OPRIS]
 CONTAINMENT = NONE
GO

ALTER DATABASE [OPRIS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OPRIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OPRIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OPRIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OPRIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OPRIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OPRIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [OPRIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OPRIS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [OPRIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OPRIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OPRIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OPRIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OPRIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OPRIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OPRIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OPRIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OPRIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OPRIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OPRIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OPRIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OPRIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OPRIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OPRIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OPRIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OPRIS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OPRIS] SET  MULTI_USER 
GO

ALTER DATABASE [OPRIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OPRIS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OPRIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OPRIS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OPRIS] SET  READ_WRITE 
GO

USE [OPRIS]
GO

/****** Object:  Table [dbo].[Account]    Script Date: 31.10.2016 00:23:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Account](
	[id] [uniqueidentifier] NOT NULL,
	[login] [nvarchar](50) NOT NULL,
	[password] [nvarchar](50) NOT NULL,
	[e_mail] [nvarchar](50) NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[User]    Script Date: 31.10.2016 00:28:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[id] [uniqueidentifier] NOT NULL,
	[surname] [nvarchar](50) NULL,
	[name] [nvarchar](50) NULL,
	[otch] [nvarchar](50) NULL,
	[city] [nvarchar](50) NULL,
	[id_account] [uniqueidentifier] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Account] FOREIGN KEY([id_account])
REFERENCES [dbo].[Account] ([id])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Account]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 31.10.2016 00:24:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Category](
	[id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Product]    Script Date: 31.10.2016 00:27:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product](
	[id] [uniqueidentifier] NOT NULL,
	[id_category] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](50) NULL,
	[price] [decimal](18, 2) NULL,
	[description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Category] FOREIGN KEY([id_category])
REFERENCES [dbo].[Category] ([id])
GO

ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Category]
GO

/****** Object:  Table [dbo].[Photo]    Script Date: 31.10.2016 00:27:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Photo](
	[id] [uniqueidentifier] NOT NULL,
	[id_product] [uniqueidentifier] NOT NULL,
	[image] [image] NULL,
 CONSTRAINT [PK_Photo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Photo]  WITH CHECK ADD  CONSTRAINT [FK_Photo_Product] FOREIGN KEY([id_product])
REFERENCES [dbo].[Product] ([id])
GO

ALTER TABLE [dbo].[Photo] CHECK CONSTRAINT [FK_Photo_Product]
GO

/****** Object:  Table [dbo].[Promo]    Script Date: 31.10.2016 00:27:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Promo](
	[id] [uniqueidentifier] NOT NULL,
	[id_account] [uniqueidentifier] NOT NULL,
	[id_product] [uniqueidentifier] NOT NULL,
	[status] [bit] NOT NULL,
	[dateStart] [date] NOT NULL,
	[dateFinish] [date] NULL,
 CONSTRAINT [PK_Promo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Promo]  WITH CHECK ADD  CONSTRAINT [FK_Promo_Account] FOREIGN KEY([id_account])
REFERENCES [dbo].[Account] ([id])
GO

ALTER TABLE [dbo].[Promo] CHECK CONSTRAINT [FK_Promo_Account]
GO

ALTER TABLE [dbo].[Promo]  WITH CHECK ADD  CONSTRAINT [FK_Promo_Product] FOREIGN KEY([id_product])
REFERENCES [dbo].[Product] ([id])
GO

ALTER TABLE [dbo].[Promo] CHECK CONSTRAINT [FK_Promo_Product]
GO

/****** Object:  Table [dbo].[Liked]    Script Date: 31.10.2016 00:25:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Liked](
	[id] [uniqueidentifier] NOT NULL,
	[id_user] [uniqueidentifier] NOT NULL,
	[id_promo] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Liked] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Liked]  WITH CHECK ADD  CONSTRAINT [FK_Liked_Promo] FOREIGN KEY([id_promo])
REFERENCES [dbo].[Promo] ([id])
GO

ALTER TABLE [dbo].[Liked] CHECK CONSTRAINT [FK_Liked_Promo]


